### ISSUE TITLE
Rework Fav Lesson functionality

### ISSUE THREAD

**Issue by drewminns** [HackerYou/chalk#129]
Currently the classroom component has an initial state value for 'favorites' but does not use it. Instead favoriting a lesson is handled by the lesson detail component via a class. To aid in interface design and UX, we should move the management to the classroom itself and pass the state down through a prop.

This is a another good use case for Redux integration since it's available through an endpoint - https://github.com/HackerYou/chalk-api/wiki/User-Endpoints#v1usercoursecourseidlessonlessonidfavorite

**Comment by Rchristiani** [comment]
Go for it, if you are doing the Redux integration already, maybe add this into the mix.

**Comment by drewminns** [comment]
References Issue #105

**Comment by Rchristiani** [comment]
Currently works, we refactor later.
