### ISSUE TITLE
Edit a topic directly from topic page

### ISSUE THREAD

**Issue by swbloom** [HackerYou/chalk#159]
Currently, editing a topic requires remembering the topic name, jumping over to the 'Topics' section and then using the search functionality to find the topic you wanted to edit.

My proposal: If you're logged in and have editing rights, each topic page has an 'edit' button that takes you directly to the page where you can edit this topic.

**Comment by Rchristiani** [comment]
Topics can be edited from a course template, not a classroom, and from there you can edit the topic. Does this work?

**Comment by swbloom** [comment]
I think this is fine, however:

Right now, in templates, we have 'Part Time HTML/CSS', 'Part Time Intro HTML/CSS', and Part Time Spring 2016 HTML/CSS. If I want to edit a specific lesson in the part time curriculum from a specific class, unless I already known which one of those templates correlates to that specific class, I'm going to have to trial and error my way through before I find the correct template. If, for example, Marki asks me to make a change to her classes notes, it's much easier for me to click 'Part Time - Marki', find the lesson, and click 'edit', then to try and figure out which template connects to her class.

Editing via template also doesn't give you a full overview of the lesson, since you still can't edit the template from the 'view' option, only the 'edit' option - you'll have to click to expand each individual section and edit them that way. This one isn't a huge deal.

What are the potential downsides of having the ability for admins to edit a lesson directly from the lesson itself?

**Comment by AlfalfaAnne** [comment]
+1 on being able to edit directly from the classroom

**Comment by Rchristiani** [comment]
So I think editing from a classroom doesn't make sense.

But a quick edit from the Course Template would make more sense. Since as stated all the content is there when creating and building a lesson, but having to go to a single topic edit page is not ideal.

**Comment by swbloom** [comment]
When you review a lesson that you're about to teach, do you do it from the Course Template or do you do it from the lesson itself? Since this is the view I would see when teaching the lesson itself, it's probably the one I would review by when preparing to teach. This means that if I notice a mistake and need to edit it, I'd have to jump into the course template to edit it first.

This functionality is similar to WordPress, where you can edit an individual page on a WordPress site from the login bar as opposed to needing to go back into the dashboard to edit the page.

This is the primary use case for me for an edit button on the lesson itself. If it doesn't get added, I'll just start reviewing lessons from the Course Template instead of from the student view to save myself having to jump back and forth.

That's the last thing I'll say about it :P

**Comment by Rchristiani** [comment]
For classroom edit functionality would you want the ability to reorder the topics as well?

Or are you just looking for the Topic edit ability?

**Comment by AlfalfaAnne** [comment]
Belatedly weighing in on this - I think it completely makes sense to have an "edit" button on the classrooms so that you can edit the topics directly from the classroom. Drag and drop isn't needed, but it's frustrating to see a quick fix that you could make and have to go all the way back to dashboard, go into course template, open up the correct class, find the correct heading (which often you need to cross-reference to doublecheck where you are in the notes), vs. just editing from the classroom. 

Additionally, it would be great if instead of defaulting to "back to topics", it would send you back to the classroom instead of having to rely on the back button. Thanks! :)
