### ISSUE TITLE
Search By Topic Name doesn't work

### ISSUE THREAD

**Issue by AlfalfaAnne** [HackerYou/chalk#165]
If I type in PT and hit return, nothing happens :(

http://cl.ly/0O2x3L24053y

**Comment by Rchristiani** [comment]
So it should work, it is just not sophisticated(simple regex right now). Typing `PT` can get you JavaScri**pt**.

Typing `PT -` will get you want you want. 

<img width="1064" alt="screen shot 2016-06-20 at 3 46 47 pm" src="https://cloud.githubusercontent.com/assets/1775147/16208057/5d0be42c-36fe-11e6-8964-12fcffa82ff0.png">

There is some work going on to add Elastic Search, and they will probably be added to that section as well.

**Comment by AlfalfaAnne** [comment]
I'm thinking this is a problem specifically with the search when you are adding a topic to a course template. http://cl.ly/2N2x3p1u2L0L

I just tried `PT - ` and a bunch of other attempts and can't get anything to come up.

http://cl.ly/2N2x3p1u2L0L

**Comment by Rchristiani** [comment]
Ohhh, yeah sorry, that is not a working thing at the moment. That is on my list of things to fix in my time off. You can filter by category, but not name yet. I am sticking around later tonight, maybe I will fix that then.

**Comment by Rchristiani** [comment]
Bug exists in https://github.com/HackerYou/chalk/blob/master/app/components/lesson-edit/index.jsx#L259
