### ISSUE TITLE
Course Templates - changes being applied to separate templates

### ISSUE THREAD

**Issue by AlfalfaAnne** [HackerYou/chalk#166]
I have been editing the `Part Time Intro HTML/CSS`, but those changes are also being applied to `Part Time HTML/CSS` template. I'm assuming this shouldn't be happening?

<img src="http://cl.ly/42411x3T0b10/Image%202016-06-22%20at%2010.55.04%20AM.png">

**Comment by Rchristiani** [comment]
No, they will show up, that has to do with how the data is linked in the API. They share the same sections. The intro one is just the intro section from the Full course.
