### ISSUE TITLE
Flag topics for editing

### ISSUE THREAD

**Issue by kristencodes** [HackerYou/chalk#186]
Sometimes we might notice mistakes/omissions mid class or when we just don't have time to fix asap. A way to quickly flag the topic for editing with a quick note about what needs to be changed would be great. Ideally a section would be visible to admin users where they could see a list and be able to mark as complete.

**Comment by Rchristiani** [comment]
I think some sort of Admin notification system would be a good idea as well. With these tests coming in and stuff like that, it would be nice to have the ability to get a notification about things happening in the system.

**Comment by Rchristiani** [comment]
Closing this as this is implemented now
