### ISSUE TITLE
Sign in button on mobile

### ISSUE THREAD

**Issue by jenthorn** [HackerYou/chalk#199]
On log in screen on mobile-
The sign in button clicks, looks like it's going to sign you in but then nothing happens.

**Comment by Rchristiani** [comment]
Interesting! 
What phone are you using?
What OS is it?
And what browser?!

Thanks

**Comment by jenthorn** [comment]
Hihihi! 
All good questions. Sorry I didn't include this!
My phone is an iPhone 6s
OS: 10.2
Browser: safari 

Let me know if you have any other questions! :)

**Comment by Rchristiani** [comment]
Hi @jenthorn, did some checking on a few iPhone 6s' here, everyone seemed to be able to log in, do you still have this issue?

**Comment by Rchristiani** [comment]
Going to close for now, hasn't seem to pop up again.
