### ISSUE TITLE
Reverse order of Classroom view

### ISSUE THREAD

**Issue by AlfalfaAnne** [HackerYou/chalk#212]
- would be great to have the classroom view updated to list from newest to oldest :)
- bit easier to find your current classroom

*Archive or ability to sort would be ideal, but I thought this might be a quick fix in the meantime.

![classroom view](https://cl.ly/2H3S3k1L1M0a/Image%202017-02-02%20at%208.53.03%20AM.png)

**Comment by Rchristiani** [comment]
Sort of basecamp like right? That is something we have been talking about. Getting a little bonkers now!

**Comment by AlfalfaAnne** [comment]
Cool! Yeah, I just figured since we are now in 2017 that the classroom list is only going to get larger 🐘 There are all sorts of fancy stuff you could implement I'm sure, but at least changing the default order would temporarily ease a pain point.

**Comment by Rchristiani** [comment]
Great, will reverse, and come up with a better long term solution!
