### ISSUE TITLE
Setting new password doesn't work

### ISSUE THREAD

**Issue by wesbos** [HackerYou/chalk#97]
When I logged in with my temp password, it asked me to set my name and new password. 

Clikcing "let's go" does nothing

![](http://wes.io/elGW/content)

**Comment by wesbos** [comment]
refreshing the page allowed me to do it

**Comment by Rchristiani** [comment]
Thanks wes! I will look into it!

**Comment by Rchristiani** [comment]
@wesbos what is the error in the console there? Just did a password reset and it went to the new page.

**Comment by wesbos** [comment]
There was not error in the console, just something about the jquery sourcemap not loading.

**Comment by Rchristiani** [comment]
Ok!

**Comment by Rchristiani** [comment]
Created a brand new user and tried to replicate. Unable to. Keep an eye on this one.

**Comment by wesbos** [comment]
I should have checked if a request went off, sorry!

**Comment by Rchristiani** [comment]
Possibly related to #103

**Comment by Rchristiani** [comment]
Issue hasn't appeared in a few months. Closing for now.
