### ISSUE TITLE
Hosted notes break SSL

### ISSUE THREAD

**Issue by wesbos** [HackerYou/chalk#98]
Try loading:

https://notes.hackeryou.com/lesson/568e90bc7886150023f3f080/56981343fd2768a62f6e3df4

Our inlined images are hosted on http so it breaks https

![](http://wes.io/ekE1/content)

**Comment by Rchristiani** [comment]
Not too worried about the mixed content thing at the moment. All the AWS images are https. There are a few links that still not on the AWS just yet.

**Comment by wesbos** [comment]
👌 makes sense!
