### ISSUE TITLE
Improve code block styling

### ISSUE THREAD

**Issue by wesbos** [HackerYou/chalk#99]
Black and dark colour schemes are hard to see on the back room projector. If we switch to a light theme with a touch larger font size it would be 👌

**Comment by drewminns** [comment]
Tested it on the back room projector and it's actually real good. We will be putting in a switch to go to a lighter scheme though.

**Comment by drewminns** [comment]
Similar to #70

**Comment by Rchristiani** [comment]
Closing this one since the details are in #70
